// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtv80s__Syms.h"


void Vtv80s___024root__trace_chg_0_sub_0(Vtv80s___024root* vlSelf, VerilatedFst::Buffer* bufp);

void Vtv80s___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_chg_0\n"); );
    // Init
    Vtv80s___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtv80s___024root*>(voidSelf);
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtv80s___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtv80s___024root__trace_chg_0_sub_0(Vtv80s___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_chg_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelfRef.reset_n));
    bufp->chgBit(oldp+1,(vlSelfRef.clk));
    bufp->chgBit(oldp+2,(vlSelfRef.wait_n));
    bufp->chgBit(oldp+3,(vlSelfRef.int_n));
    bufp->chgBit(oldp+4,(vlSelfRef.nmi_n));
    bufp->chgBit(oldp+5,(vlSelfRef.busrq_n));
    bufp->chgBit(oldp+6,(vlSelfRef.m1_n));
    bufp->chgBit(oldp+7,(vlSelfRef.mreq_n));
    bufp->chgBit(oldp+8,(vlSelfRef.iorq_n));
    bufp->chgBit(oldp+9,(vlSelfRef.rd_n));
    bufp->chgBit(oldp+10,(vlSelfRef.wr_n));
    bufp->chgBit(oldp+11,(vlSelfRef.rfsh_n));
    bufp->chgBit(oldp+12,(vlSelfRef.halt_n));
    bufp->chgBit(oldp+13,(vlSelfRef.busak_n));
    bufp->chgSData(oldp+14,(vlSelfRef.A),16);
    bufp->chgCData(oldp+15,(vlSelfRef.di),8);
    bufp->chgCData(oldp+16,(vlSelfRef.dout),8);
    bufp->chgBit(oldp+17,(vlSelfRef.tv80s__DOT__reset_n));
    bufp->chgBit(oldp+18,(vlSelfRef.tv80s__DOT__clk));
    bufp->chgBit(oldp+19,(vlSelfRef.tv80s__DOT__wait_n));
    bufp->chgBit(oldp+20,(vlSelfRef.tv80s__DOT__int_n));
    bufp->chgBit(oldp+21,(vlSelfRef.tv80s__DOT__nmi_n));
    bufp->chgBit(oldp+22,(vlSelfRef.tv80s__DOT__busrq_n));
    bufp->chgBit(oldp+23,(vlSelfRef.tv80s__DOT__m1_n));
    bufp->chgBit(oldp+24,(vlSelfRef.tv80s__DOT__mreq_n));
    bufp->chgBit(oldp+25,(vlSelfRef.tv80s__DOT__iorq_n));
    bufp->chgBit(oldp+26,(vlSelfRef.tv80s__DOT__rd_n));
    bufp->chgBit(oldp+27,(vlSelfRef.tv80s__DOT__wr_n));
    bufp->chgBit(oldp+28,(vlSelfRef.tv80s__DOT__rfsh_n));
    bufp->chgBit(oldp+29,(vlSelfRef.tv80s__DOT__halt_n));
    bufp->chgBit(oldp+30,(vlSelfRef.tv80s__DOT__busak_n));
    bufp->chgSData(oldp+31,(vlSelfRef.tv80s__DOT__A),16);
    bufp->chgCData(oldp+32,(vlSelfRef.tv80s__DOT__di),8);
    bufp->chgCData(oldp+33,(vlSelfRef.tv80s__DOT__dout),8);
    bufp->chgBit(oldp+34,(vlSelfRef.tv80s__DOT__cen));
    bufp->chgBit(oldp+35,(vlSelfRef.tv80s__DOT__intcycle_n));
    bufp->chgBit(oldp+36,(vlSelfRef.tv80s__DOT__no_read));
    bufp->chgBit(oldp+37,(vlSelfRef.tv80s__DOT__write));
    bufp->chgBit(oldp+38,(vlSelfRef.tv80s__DOT__iorq));
    bufp->chgCData(oldp+39,(vlSelfRef.tv80s__DOT__di_reg),8);
    bufp->chgCData(oldp+40,(vlSelfRef.tv80s__DOT__mcycle),7);
    bufp->chgCData(oldp+41,(vlSelfRef.tv80s__DOT__tstate),7);
    bufp->chgBit(oldp+42,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__reset_n));
    bufp->chgBit(oldp+43,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__clk));
    bufp->chgBit(oldp+44,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__cen));
    bufp->chgBit(oldp+45,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__wait_n));
    bufp->chgBit(oldp+46,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__int_n));
    bufp->chgBit(oldp+47,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__nmi_n));
    bufp->chgBit(oldp+48,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__busrq_n));
    bufp->chgBit(oldp+49,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__m1_n));
    bufp->chgBit(oldp+50,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__iorq));
    bufp->chgBit(oldp+51,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__no_read));
    bufp->chgBit(oldp+52,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__write));
    bufp->chgBit(oldp+53,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__rfsh_n));
    bufp->chgBit(oldp+54,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__halt_n));
    bufp->chgBit(oldp+55,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__busak_n));
    bufp->chgSData(oldp+56,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__A),16);
    bufp->chgCData(oldp+57,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__dinst),8);
    bufp->chgCData(oldp+58,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__di),8);
    bufp->chgCData(oldp+59,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__dout),8);
    bufp->chgCData(oldp+60,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mc),7);
    bufp->chgCData(oldp+61,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ts),7);
    bufp->chgBit(oldp+62,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__intcycle_n));
    bufp->chgBit(oldp+63,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntE));
    bufp->chgBit(oldp+64,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__stop));
    bufp->chgCData(oldp+65,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ACC),8);
    bufp->chgCData(oldp+66,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__F),8);
    bufp->chgCData(oldp+67,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Ap),8);
    bufp->chgCData(oldp+68,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Fp),8);
    bufp->chgCData(oldp+69,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I),8);
    bufp->chgSData(oldp+70,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP),16);
    bufp->chgSData(oldp+71,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PC),16);
    bufp->chgCData(oldp+72,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegDIH),8);
    bufp->chgCData(oldp+73,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegDIL),8);
    bufp->chgSData(oldp+74,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusA),16);
    bufp->chgSData(oldp+75,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusB),16);
    bufp->chgSData(oldp+76,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusC),16);
    bufp->chgCData(oldp+77,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrA_r),3);
    bufp->chgCData(oldp+78,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrA),3);
    bufp->chgCData(oldp+79,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrB_r),3);
    bufp->chgCData(oldp+80,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrB),3);
    bufp->chgCData(oldp+81,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrC),3);
    bufp->chgBit(oldp+82,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegWEH));
    bufp->chgBit(oldp+83,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegWEL));
    bufp->chgBit(oldp+84,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Alternate));
    bufp->chgSData(oldp+85,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__TmpAddr),16);
    bufp->chgCData(oldp+86,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IR),8);
    bufp->chgCData(oldp+87,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ISet),2);
    bufp->chgSData(oldp+88,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusA_r),16);
    bufp->chgBit(oldp+89,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__reset_4x));
    bufp->chgSData(oldp+90,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ID16),16);
    bufp->chgCData(oldp+91,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Save_Mux),8);
    bufp->chgCData(oldp+92,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__tstate),7);
    bufp->chgCData(oldp+93,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mcycle),7);
    bufp->chgBit(oldp+94,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__last_mcycle));
    bufp->chgBit(oldp+95,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__last_tstate));
    bufp->chgBit(oldp+96,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntE_FF1));
    bufp->chgBit(oldp+97,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntE_FF2));
    bufp->chgBit(oldp+98,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Halt_FF));
    bufp->chgBit(oldp+99,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusReq_s));
    bufp->chgBit(oldp+100,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusAck));
    bufp->chgBit(oldp+101,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ClkEn));
    bufp->chgBit(oldp+102,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__NMI_s));
    bufp->chgBit(oldp+103,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__INT_s));
    bufp->chgCData(oldp+104,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IStatus),2);
    bufp->chgCData(oldp+105,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__DI_Reg),8);
    bufp->chgBit(oldp+106,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__T_Res));
    bufp->chgCData(oldp+107,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__XY_State),2);
    bufp->chgCData(oldp+108,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Pre_XY_F_M),3);
    bufp->chgBit(oldp+109,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__NextIs_XY_Fetch));
    bufp->chgBit(oldp+110,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__XY_Ind));
    bufp->chgBit(oldp+111,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__No_BTR));
    bufp->chgBit(oldp+112,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BTR_r));
    bufp->chgBit(oldp+113,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Auto_Wait));
    bufp->chgBit(oldp+114,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Auto_Wait_t1));
    bufp->chgBit(oldp+115,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Auto_Wait_t2));
    bufp->chgBit(oldp+116,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IncDecZ));
    bufp->chgCData(oldp+117,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusB),8);
    bufp->chgCData(oldp+118,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusA),8);
    bufp->chgCData(oldp+119,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ALU_Q),8);
    bufp->chgCData(oldp+120,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__F_Out),8);
    bufp->chgCData(oldp+121,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Read_To_Reg_r),5);
    bufp->chgBit(oldp+122,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Arith16_r));
    bufp->chgBit(oldp+123,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Z16_r));
    bufp->chgCData(oldp+124,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ALU_Op_r),4);
    bufp->chgBit(oldp+125,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Save_ALU_r));
    bufp->chgBit(oldp+126,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PreserveC_r));
    bufp->chgCData(oldp+127,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mcycles),3);
    bufp->chgCData(oldp+128,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mcycles_d),3);
    bufp->chgCData(oldp+129,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__tstates),3);
    bufp->chgBit(oldp+130,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntCycle));
    bufp->chgBit(oldp+131,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__NMICycle));
    bufp->chgBit(oldp+132,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Inc_PC));
    bufp->chgBit(oldp+133,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Inc_WZ));
    bufp->chgCData(oldp+134,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IncDec_16),4);
    bufp->chgCData(oldp+135,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Prefix),2);
    bufp->chgBit(oldp+136,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Read_To_Acc));
    bufp->chgBit(oldp+137,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Read_To_Reg));
    bufp->chgCData(oldp+138,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Set_BusB_To),4);
    bufp->chgCData(oldp+139,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Set_BusA_To),4);
    bufp->chgCData(oldp+140,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ALU_Op),4);
    bufp->chgBit(oldp+141,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Save_ALU));
    bufp->chgBit(oldp+142,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PreserveC));
    bufp->chgBit(oldp+143,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Arith16));
    bufp->chgCData(oldp+144,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Set_Addr_To),3);
    bufp->chgBit(oldp+145,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Jump));
    bufp->chgBit(oldp+146,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__JumpE));
    bufp->chgBit(oldp+147,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__JumpXY));
    bufp->chgBit(oldp+148,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Call));
    bufp->chgBit(oldp+149,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RstP));
    bufp->chgBit(oldp+150,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__LDZ));
    bufp->chgBit(oldp+151,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__LDW));
    bufp->chgBit(oldp+152,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__LDSPHL));
    bufp->chgBit(oldp+153,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__iorq_i));
    bufp->chgBit(oldp+154,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__will_iorq));
    bufp->chgCData(oldp+155,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Special_LD),3);
    bufp->chgBit(oldp+156,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeDH));
    bufp->chgBit(oldp+157,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeRp));
    bufp->chgBit(oldp+158,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeAF));
    bufp->chgBit(oldp+159,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeRS));
    bufp->chgBit(oldp+160,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_DJNZ));
    bufp->chgBit(oldp+161,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_CPL));
    bufp->chgBit(oldp+162,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_CCF));
    bufp->chgBit(oldp+163,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_SCF));
    bufp->chgBit(oldp+164,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_RETN));
    bufp->chgBit(oldp+165,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_BT));
    bufp->chgBit(oldp+166,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_BC));
    bufp->chgBit(oldp+167,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_BTR));
    bufp->chgBit(oldp+168,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_RLD));
    bufp->chgBit(oldp+169,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_RRD));
    bufp->chgBit(oldp+170,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_INRC));
    bufp->chgBit(oldp+171,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SetDI));
    bufp->chgBit(oldp+172,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SetEI));
    bufp->chgCData(oldp+173,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IMode),2);
    bufp->chgBit(oldp+174,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Halt));
    bufp->chgSData(oldp+175,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PC16),16);
    bufp->chgSData(oldp+176,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PC16_B),16);
    bufp->chgSData(oldp+177,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP16),16);
    bufp->chgSData(oldp+178,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP16_A),16);
    bufp->chgSData(oldp+179,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP16_B),16);
    bufp->chgSData(oldp+180,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ID16_B),16);
    bufp->chgBit(oldp+181,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Oldnmi_n));
    bufp->chgBit(oldp+182,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Arith16));
    bufp->chgBit(oldp+183,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Z16));
    bufp->chgCData(oldp+184,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__ALU_Op),4);
    bufp->chgCData(oldp+185,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__IR),6);
    bufp->chgCData(oldp+186,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__ISet),2);
    bufp->chgCData(oldp+187,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BusA),8);
    bufp->chgCData(oldp+188,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BusB),8);
    bufp->chgCData(oldp+189,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__F_In),8);
    bufp->chgCData(oldp+190,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q),8);
    bufp->chgCData(oldp+191,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__F_Out),8);
    bufp->chgBit(oldp+192,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__UseCarry));
    bufp->chgBit(oldp+193,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Carry7_v));
    bufp->chgBit(oldp+194,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__OverFlow_v));
    bufp->chgBit(oldp+195,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__HalfCarry_v));
    bufp->chgBit(oldp+196,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Carry_v));
    bufp->chgCData(oldp+197,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q_v),8);
    bufp->chgCData(oldp+198,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BitMask),8);
    bufp->chgCData(oldp+199,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q_t),8);
    bufp->chgSData(oldp+200,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__DAA_Q),9);
    bufp->chgCData(oldp+201,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IR),8);
    bufp->chgCData(oldp+202,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ISet),2);
    bufp->chgCData(oldp+203,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycle),7);
    bufp->chgCData(oldp+204,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__F),8);
    bufp->chgBit(oldp+205,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__NMICycle));
    bufp->chgBit(oldp+206,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IntCycle));
    bufp->chgCData(oldp+207,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycles),3);
    bufp->chgCData(oldp+208,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__TStates),3);
    bufp->chgCData(oldp+209,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Prefix),2);
    bufp->chgBit(oldp+210,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_PC));
    bufp->chgBit(oldp+211,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_WZ));
    bufp->chgCData(oldp+212,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IncDec_16),4);
    bufp->chgBit(oldp+213,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Reg));
    bufp->chgBit(oldp+214,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Acc));
    bufp->chgCData(oldp+215,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusA_To),4);
    bufp->chgCData(oldp+216,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusB_To),4);
    bufp->chgCData(oldp+217,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ALU_Op),4);
    bufp->chgBit(oldp+218,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Save_ALU));
    bufp->chgBit(oldp+219,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__PreserveC));
    bufp->chgBit(oldp+220,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Arith16));
    bufp->chgCData(oldp+221,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_Addr_To),3);
    bufp->chgBit(oldp+222,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IORQ));
    bufp->chgBit(oldp+223,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__WILL_IORQ));
    bufp->chgBit(oldp+224,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Jump));
    bufp->chgBit(oldp+225,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpE));
    bufp->chgBit(oldp+226,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpXY));
    bufp->chgBit(oldp+227,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Call));
    bufp->chgBit(oldp+228,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__RstP));
    bufp->chgBit(oldp+229,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDZ));
    bufp->chgBit(oldp+230,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDW));
    bufp->chgBit(oldp+231,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDSPHL));
    bufp->chgCData(oldp+232,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Special_LD),3);
    bufp->chgBit(oldp+233,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeDH));
    bufp->chgBit(oldp+234,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRp));
    bufp->chgBit(oldp+235,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeAF));
    bufp->chgBit(oldp+236,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRS));
    bufp->chgBit(oldp+237,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_DJNZ));
    bufp->chgBit(oldp+238,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CPL));
    bufp->chgBit(oldp+239,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CCF));
    bufp->chgBit(oldp+240,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_SCF));
    bufp->chgBit(oldp+241,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RETN));
    bufp->chgBit(oldp+242,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BT));
    bufp->chgBit(oldp+243,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BC));
    bufp->chgBit(oldp+244,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BTR));
    bufp->chgBit(oldp+245,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RLD));
    bufp->chgBit(oldp+246,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RRD));
    bufp->chgBit(oldp+247,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_INRC));
    bufp->chgBit(oldp+248,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SetDI));
    bufp->chgBit(oldp+249,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SetEI));
    bufp->chgCData(oldp+250,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IMode),2);
    bufp->chgBit(oldp+251,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Halt));
    bufp->chgBit(oldp+252,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__NoRead));
    bufp->chgBit(oldp+253,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Write));
    bufp->chgCData(oldp+254,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__DDD),3);
    bufp->chgCData(oldp+255,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SSS),3);
    bufp->chgCData(oldp+256,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__DPAIR),2);
    bufp->chgCData(oldp+257,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrC),3);
    bufp->chgCData(oldp+258,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOBH),8);
    bufp->chgCData(oldp+259,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrA),3);
    bufp->chgCData(oldp+260,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrB),3);
    bufp->chgCData(oldp+261,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DIH),8);
    bufp->chgCData(oldp+262,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOAL),8);
    bufp->chgCData(oldp+263,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOCL),8);
    bufp->chgCData(oldp+264,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DIL),8);
    bufp->chgCData(oldp+265,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOBL),8);
    bufp->chgCData(oldp+266,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOCH),8);
    bufp->chgCData(oldp+267,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOAH),8);
    bufp->chgBit(oldp+268,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__clk));
    bufp->chgBit(oldp+269,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__CEN));
    bufp->chgBit(oldp+270,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__WEH));
    bufp->chgBit(oldp+271,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__WEL));
    bufp->chgCData(oldp+272,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[0]),8);
    bufp->chgCData(oldp+273,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[1]),8);
    bufp->chgCData(oldp+274,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[2]),8);
    bufp->chgCData(oldp+275,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[3]),8);
    bufp->chgCData(oldp+276,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[4]),8);
    bufp->chgCData(oldp+277,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[5]),8);
    bufp->chgCData(oldp+278,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[6]),8);
    bufp->chgCData(oldp+279,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[7]),8);
    bufp->chgCData(oldp+280,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[0]),8);
    bufp->chgCData(oldp+281,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[1]),8);
    bufp->chgCData(oldp+282,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[2]),8);
    bufp->chgCData(oldp+283,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[3]),8);
    bufp->chgCData(oldp+284,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[4]),8);
    bufp->chgCData(oldp+285,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[5]),8);
    bufp->chgCData(oldp+286,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[6]),8);
    bufp->chgCData(oldp+287,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[7]),8);
    bufp->chgCData(oldp+288,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__B),8);
    bufp->chgCData(oldp+289,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__C),8);
    bufp->chgCData(oldp+290,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__D),8);
    bufp->chgCData(oldp+291,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__E),8);
    bufp->chgCData(oldp+292,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__H),8);
    bufp->chgCData(oldp+293,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__L),8);
    bufp->chgSData(oldp+294,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__IX),16);
    bufp->chgSData(oldp+295,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__IY),16);
}

void Vtv80s___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_cleanup\n"); );
    // Init
    Vtv80s___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtv80s___024root*>(voidSelf);
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
