// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtv80s.h for the primary calling header

#ifndef VERILATED_VTV80S___024ROOT_H_
#define VERILATED_VTV80S___024ROOT_H_  // guard

#include "verilated.h"


class Vtv80s__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtv80s___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    VL_IN8(reset_n,0,0);
    VL_IN8(clk,0,0);
    VL_IN8(wait_n,0,0);
    CData/*0:0*/ tv80s__DOT__cen;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Alternate;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__last_tstate;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__IntE_FF1;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Halt_FF;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__BusAck;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__XY_Ind;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__BTR_r;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Auto_Wait_t1;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Arith16_r;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Z16_r;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Save_ALU_r;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__IntCycle;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__NMICycle;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__JumpE;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__iorq_i;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__ExchangeDH;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__ExchangeRp;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_DJNZ;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__OverFlow_v;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__HalfCarry_v;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Carry_v;
    VL_OUT8(m1_n,0,0);
    VL_OUT8(mreq_n,0,0);
    VL_OUT8(iorq_n,0,0);
    VL_OUT8(rd_n,0,0);
    VL_OUT8(wr_n,0,0);
    VL_OUT8(rfsh_n,0,0);
    VL_OUT8(halt_n,0,0);
    VL_OUT8(busak_n,0,0);
    VL_OUT8(dout,7,0);
    VL_IN8(int_n,0,0);
    VL_IN8(nmi_n,0,0);
    VL_IN8(busrq_n,0,0);
    VL_IN8(di,7,0);
    CData/*0:0*/ tv80s__DOT__m1_n;
    CData/*0:0*/ tv80s__DOT__mreq_n;
    CData/*0:0*/ tv80s__DOT__iorq_n;
    CData/*0:0*/ tv80s__DOT__rd_n;
    CData/*0:0*/ tv80s__DOT__wr_n;
    CData/*0:0*/ tv80s__DOT__rfsh_n;
    CData/*0:0*/ tv80s__DOT__halt_n;
    CData/*0:0*/ tv80s__DOT__busak_n;
    CData/*7:0*/ tv80s__DOT__dout;
    CData/*0:0*/ tv80s__DOT__reset_n;
    CData/*0:0*/ tv80s__DOT__clk;
    CData/*0:0*/ tv80s__DOT__wait_n;
    CData/*0:0*/ tv80s__DOT__int_n;
    CData/*0:0*/ tv80s__DOT__nmi_n;
    CData/*0:0*/ tv80s__DOT__busrq_n;
    CData/*7:0*/ tv80s__DOT__di;
    CData/*0:0*/ tv80s__DOT__intcycle_n;
    CData/*0:0*/ tv80s__DOT__no_read;
    CData/*0:0*/ tv80s__DOT__write;
    CData/*0:0*/ tv80s__DOT__iorq;
    CData/*7:0*/ tv80s__DOT__di_reg;
    CData/*6:0*/ tv80s__DOT__mcycle;
    CData/*6:0*/ tv80s__DOT__tstate;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__m1_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__iorq;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__no_read;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__write;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__rfsh_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__halt_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__busak_n;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__dout;
    CData/*6:0*/ tv80s__DOT__i_tv80_core__DOT__mc;
    CData/*6:0*/ tv80s__DOT__i_tv80_core__DOT__ts;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__intcycle_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__IntE;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__stop;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__reset_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__clk;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__cen;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__wait_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__int_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__nmi_n;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__busrq_n;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__dinst;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__di;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__ACC;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__F;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__Ap;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__Fp;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__I;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__RegDIH;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__RegDIL;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__RegAddrA_r;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__RegAddrA;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__RegAddrB_r;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__RegAddrB;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__RegAddrC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__RegWEH;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__RegWEL;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__IR;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__ISet;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__Save_Mux;
    CData/*6:0*/ tv80s__DOT__i_tv80_core__DOT__tstate;
    CData/*6:0*/ tv80s__DOT__i_tv80_core__DOT__mcycle;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__last_mcycle;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__IntE_FF2;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__BusReq_s;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__ClkEn;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__NMI_s;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__INT_s;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__IStatus;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__DI_Reg;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__T_Res;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__XY_State;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__Pre_XY_F_M;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__NextIs_XY_Fetch;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__No_BTR;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Auto_Wait;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Auto_Wait_t2;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__IncDecZ;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__BusB;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__BusA;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__ALU_Q;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__F_Out;
    CData/*4:0*/ tv80s__DOT__i_tv80_core__DOT__Read_To_Reg_r;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__ALU_Op_r;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__PreserveC_r;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__mcycles;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__mcycles_d;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__tstates;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Inc_PC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Inc_WZ;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__IncDec_16;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__Prefix;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Read_To_Acc;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Read_To_Reg;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__Set_BusB_To;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__Set_BusA_To;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__ALU_Op;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Save_ALU;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__PreserveC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Arith16;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__Set_Addr_To;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Jump;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__JumpXY;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Call;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__RstP;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__LDZ;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__LDW;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__LDSPHL;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__Special_LD;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__ExchangeAF;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__ExchangeRS;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_CPL;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_CCF;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_SCF;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_RETN;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_BT;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_BC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_BTR;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_RLD;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_RRD;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__I_INRC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__SetDI;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__SetEI;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__IMode;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Halt;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__Oldnmi_n;
    CData/*5:0*/ tv80s__DOT__i_tv80_core__DOT____Vcellinp__i_alu__IR;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycles;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__TStates;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Prefix;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_PC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_WZ;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IncDec_16;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Reg;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Acc;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusA_To;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusB_To;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ALU_Op;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Save_ALU;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__PreserveC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Arith16;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_Addr_To;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IORQ;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Jump;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpE;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpXY;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Call;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__RstP;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDZ;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDW;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDSPHL;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Special_LD;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeDH;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRp;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeAF;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRS;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_DJNZ;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CPL;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CCF;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_SCF;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RETN;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BT;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BTR;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RLD;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RRD;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_INRC;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SetDI;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SetEI;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IMode;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Halt;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__NoRead;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Write;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IR;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ISet;
    CData/*6:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycle;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__F;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__NMICycle;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IntCycle;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__DDD;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SSS;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__DPAIR;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__F_Out;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Arith16;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Z16;
    CData/*3:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__ALU_Op;
    CData/*5:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__IR;
    CData/*1:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__ISet;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BusA;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BusB;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__F_In;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__UseCarry;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Carry7_v;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q_v;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BitMask;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q_t;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOBH;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOAL;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOCL;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOBL;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOCH;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOAH;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrC;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrA;
    CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrB;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DIH;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DIL;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__clk;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__CEN;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__WEH;
    CData/*0:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__WEL;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__B;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__C;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__D;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__E;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__H;
    CData/*7:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__L;
    CData/*1:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__XY_State;
    CData/*7:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__IR;
    CData/*7:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__ACC;
    CData/*7:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__F;
    CData/*0:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__Alternate;
    CData/*6:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__tstate;
    CData/*6:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__mcycle;
    CData/*0:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__IntCycle;
    CData/*0:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__NMICycle;
    CData/*0:0*/ __VstlFirstIteration;
    CData/*0:0*/ __VicoFirstIteration;
    CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__reset_n__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__F__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__IR__0;
    CData/*1:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__ISet__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__IntCycle__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__NMICycle__0;
    CData/*6:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__mcycle__0;
    CData/*3:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__ALU_Op_r__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__BusA__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT__BusB__0;
    CData/*5:0*/ __Vtrigprevexpr___TOP__tv80s__DOT__i_tv80_core__DOT____Vcellinp__i_alu__IR__0;
    CData/*0:0*/ __VactDidInit;
    CData/*0:0*/ __VactContinue;
    VL_OUT16(A,15,0);
    SData/*15:0*/ tv80s__DOT__A;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__A;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__SP;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__PC;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__RegBusA;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__RegBusB;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__RegBusC;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__TmpAddr;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__RegBusA_r;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__ID16;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__PC16;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__PC16_B;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__SP16;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__SP16_A;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__SP16_B;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__ID16_B;
    SData/*8:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__DAA_Q;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__IX;
    SData/*15:0*/ tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__IY;
    SData/*15:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__PC;
    SData/*15:0*/ __Vdly__tv80s__DOT__i_tv80_core__DOT__SP;
    IData/*31:0*/ __VactIterCount;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<12> __VactTriggered;
    VlTriggerVec<12> __VnbaTriggered;
    VlUnpacked<CData/*7:0*/, 8> tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH;
    VlUnpacked<CData/*7:0*/, 8> tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL;

    // INTERNAL VARIABLES
    Vtv80s__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__aNone = 7U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__aBC = 0U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__aDE = 1U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__aXY = 2U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__aIOA = 4U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__aSP = 5U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__aZI = 6U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__aNone = 7U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__aBC = 0U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__aDE = 1U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__aXY = 2U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__aIOA = 4U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__aSP = 5U;
    static constexpr CData/*2:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__aZI = 6U;
    static constexpr IData/*31:0*/ tv80s__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ tv80s__DOT__T2Write = 1U;
    static constexpr IData/*31:0*/ tv80s__DOT__IOWait = 1U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__IOWait = 1U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_C = 0U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_N = 1U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_P = 2U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_X = 3U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_H = 4U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_Y = 5U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_Z = 6U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__Flag_S = 7U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_C = 0U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_N = 1U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_P = 2U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_X = 3U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_H = 4U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_Y = 5U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_Z = 6U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_S = 7U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_C = 0U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_N = 1U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_P = 2U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_X = 3U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_H = 4U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_Y = 5U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_Z = 6U;
    static constexpr IData/*31:0*/ tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_S = 7U;

    // CONSTRUCTORS
    Vtv80s___024root(Vtv80s__Syms* symsp, const char* v__name);
    ~Vtv80s___024root();
    VL_UNCOPYABLE(Vtv80s___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
