// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtv80s__Syms.h"


VL_ATTR_COLD void Vtv80s___024root__trace_init_sub__TOP__0(Vtv80s___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_init_sub__TOP__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"reset_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"wait_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"int_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+5,0,"nmi_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+6,0,"busrq_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"m1_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+8,0,"mreq_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"iorq_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"rd_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"wr_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+12,0,"rfsh_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+13,0,"halt_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"busak_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+15,0,"A",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+16,0,"di",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+17,0,"dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("tv80s", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+297,0,"Mode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"T2Write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"IOWait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+18,0,"reset_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"wait_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"int_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+22,0,"nmi_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"busrq_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"m1_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"mreq_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"iorq_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"rd_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"wr_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"rfsh_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"halt_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"busak_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+32,0,"A",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+33,0,"di",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+34,0,"dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+35,0,"cen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"intcycle_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"no_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"iorq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"di_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+41,0,"mcycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+42,0,"tstate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->pushPrefix("i_tv80_core", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+297,0,"Mode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"IOWait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+299,0,"Flag_C",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+300,0,"Flag_N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+301,0,"Flag_P",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"Flag_X",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+302,0,"Flag_H",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+303,0,"Flag_Y",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+304,0,"Flag_Z",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+297,0,"Flag_S",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+43,0,"reset_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+44,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+45,0,"cen",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"wait_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"int_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"nmi_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"busrq_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"m1_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+51,0,"iorq",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+52,0,"no_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+53,0,"write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"rfsh_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"halt_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+56,0,"busak_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+57,0,"A",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+58,0,"dinst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+59,0,"di",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+60,0,"dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+61,0,"mc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+62,0,"ts",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+63,0,"intcycle_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+64,0,"IntE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+65,0,"stop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+305,0,"aNone",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+306,0,"aBC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+307,0,"aDE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+308,0,"aXY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+309,0,"aIOA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+310,0,"aSP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+311,0,"aZI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+66,0,"ACC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+67,0,"F",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+68,0,"Ap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+69,0,"Fp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+70,0,"I",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+71,0,"SP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+72,0,"PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+73,0,"RegDIH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+74,0,"RegDIL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+75,0,"RegBusA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+76,0,"RegBusB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+77,0,"RegBusC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+78,0,"RegAddrA_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+79,0,"RegAddrA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+80,0,"RegAddrB_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+81,0,"RegAddrB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+82,0,"RegAddrC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+83,0,"RegWEH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"RegWEL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+85,0,"Alternate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+86,0,"TmpAddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+87,0,"IR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+88,0,"ISet",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+89,0,"RegBusA_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+90,0,"reset_4x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+91,0,"ID16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+92,0,"Save_Mux",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+93,0,"tstate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+94,0,"mcycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+95,0,"last_mcycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"last_tstate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"IntE_FF1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"IntE_FF2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"Halt_FF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+100,0,"BusReq_s",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+101,0,"BusAck",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+102,0,"ClkEn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+103,0,"NMI_s",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+104,0,"INT_s",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+105,0,"IStatus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+106,0,"DI_Reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+107,0,"T_Res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+108,0,"XY_State",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+109,0,"Pre_XY_F_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+110,0,"NextIs_XY_Fetch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"XY_Ind",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+112,0,"No_BTR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+113,0,"BTR_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"Auto_Wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"Auto_Wait_t1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"Auto_Wait_t2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"IncDecZ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+118,0,"BusB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+119,0,"BusA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+120,0,"ALU_Q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+121,0,"F_Out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+122,0,"Read_To_Reg_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+123,0,"Arith16_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"Z16_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+125,0,"ALU_Op_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+126,0,"Save_ALU_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"PreserveC_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+128,0,"mcycles",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+129,0,"mcycles_d",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+130,0,"tstates",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+131,0,"IntCycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"NMICycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+133,0,"Inc_PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"Inc_WZ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+135,0,"IncDec_16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+136,0,"Prefix",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+137,0,"Read_To_Acc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"Read_To_Reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+139,0,"Set_BusB_To",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+140,0,"Set_BusA_To",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+141,0,"ALU_Op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+142,0,"Save_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"PreserveC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"Arith16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+145,0,"Set_Addr_To",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+146,0,"Jump",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"JumpE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"JumpXY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"Call",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"RstP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"LDZ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"LDW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"LDSPHL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"iorq_i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"will_iorq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+156,0,"Special_LD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+157,0,"ExchangeDH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"ExchangeRp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"ExchangeAF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"ExchangeRS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"I_DJNZ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"I_CPL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+163,0,"I_CCF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"I_SCF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"I_RETN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"I_BT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"I_BC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+168,0,"I_BTR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+169,0,"I_RLD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+170,0,"I_RRD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"I_INRC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"SetDI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"SetEI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+174,0,"IMode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+175,0,"Halt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+176,0,"PC16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+177,0,"PC16_B",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+178,0,"SP16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+179,0,"SP16_A",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+180,0,"SP16_B",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+181,0,"ID16_B",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+182,0,"Oldnmi_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("i_alu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+297,0,"Mode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+299,0,"Flag_C",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+300,0,"Flag_N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+301,0,"Flag_P",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"Flag_X",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+302,0,"Flag_H",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+303,0,"Flag_Y",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+304,0,"Flag_Z",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+297,0,"Flag_S",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+183,0,"Arith16",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+184,0,"Z16",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+185,0,"ALU_Op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+186,0,"IR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+187,0,"ISet",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+188,0,"BusA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+189,0,"BusB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+190,0,"F_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+191,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+192,0,"F_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+193,0,"UseCarry",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+194,0,"Carry7_v",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+195,0,"OverFlow_v",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+196,0,"HalfCarry_v",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"Carry_v",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+198,0,"Q_v",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+199,0,"BitMask",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+200,0,"Q_t",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+201,0,"DAA_Q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->popPrefix();
    tracep->pushPrefix("i_mcode", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+297,0,"Mode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+299,0,"Flag_C",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+300,0,"Flag_N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+301,0,"Flag_P",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"Flag_X",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+302,0,"Flag_H",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+303,0,"Flag_Y",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+304,0,"Flag_Z",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+297,0,"Flag_S",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"IR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+203,0,"ISet",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+204,0,"MCycle",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+205,0,"F",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+206,0,"NMICycle",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+207,0,"IntCycle",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+208,0,"MCycles",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+209,0,"TStates",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+210,0,"Prefix",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+211,0,"Inc_PC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+212,0,"Inc_WZ",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+213,0,"IncDec_16",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+214,0,"Read_To_Reg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"Read_To_Acc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+216,0,"Set_BusA_To",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+217,0,"Set_BusB_To",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+218,0,"ALU_Op",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+219,0,"Save_ALU",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+220,0,"PreserveC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"Arith16",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+222,0,"Set_Addr_To",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+223,0,"IORQ",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+224,0,"WILL_IORQ",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+225,0,"Jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+226,0,"JumpE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+227,0,"JumpXY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+228,0,"Call",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"RstP",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+230,0,"LDZ",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+231,0,"LDW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+232,0,"LDSPHL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+233,0,"Special_LD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+234,0,"ExchangeDH",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"ExchangeRp",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+236,0,"ExchangeAF",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+237,0,"ExchangeRS",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+238,0,"I_DJNZ",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+239,0,"I_CPL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"I_CCF",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+241,0,"I_SCF",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+242,0,"I_RETN",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+243,0,"I_BT",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+244,0,"I_BC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"I_BTR",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+246,0,"I_RLD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+247,0,"I_RRD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+248,0,"I_INRC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+249,0,"SetDI",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+250,0,"SetEI",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+251,0,"IMode",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+252,0,"Halt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+253,0,"NoRead",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+254,0,"Write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+305,0,"aNone",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+306,0,"aBC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+307,0,"aDE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+308,0,"aXY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+309,0,"aIOA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+310,0,"aSP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+311,0,"aZI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+255,0,"DDD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+256,0,"SSS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+257,0,"DPAIR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("i_reg", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+258,0,"AddrC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+259,0,"DOBH",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+260,0,"AddrA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+261,0,"AddrB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+262,0,"DIH",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+263,0,"DOAL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+264,0,"DOCL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+265,0,"DIL",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+266,0,"DOBL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+267,0,"DOCH",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+268,0,"DOAH",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+269,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+270,0,"CEN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+271,0,"WEH",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+272,0,"WEL",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("RegsH", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 8; ++i) {
        tracep->declBus(c+273+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("RegsL", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 8; ++i) {
        tracep->declBus(c+281+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+289,0,"B",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+290,0,"C",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+291,0,"D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+292,0,"E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+293,0,"H",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+294,0,"L",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+295,0,"IX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+296,0,"IY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtv80s___024root__trace_init_top(Vtv80s___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_init_top\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtv80s___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtv80s___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp);
VL_ATTR_COLD void Vtv80s___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtv80s___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtv80s___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtv80s___024root__trace_register(Vtv80s___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_register\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtv80s___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtv80s___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtv80s___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtv80s___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtv80s___024root__trace_const_0_sub_0(Vtv80s___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtv80s___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_const_0\n"); );
    // Init
    Vtv80s___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtv80s___024root*>(voidSelf);
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtv80s___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtv80s___024root__trace_const_0_sub_0(Vtv80s___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_const_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+297,(3U),32);
    bufp->fullIData(oldp+298,(1U),32);
    bufp->fullIData(oldp+299,(4U),32);
    bufp->fullIData(oldp+300,(6U),32);
    bufp->fullIData(oldp+301,(0U),32);
    bufp->fullIData(oldp+302,(5U),32);
    bufp->fullIData(oldp+303,(2U),32);
    bufp->fullIData(oldp+304,(7U),32);
    bufp->fullCData(oldp+305,(7U),3);
    bufp->fullCData(oldp+306,(0U),3);
    bufp->fullCData(oldp+307,(1U),3);
    bufp->fullCData(oldp+308,(2U),3);
    bufp->fullCData(oldp+309,(4U),3);
    bufp->fullCData(oldp+310,(5U),3);
    bufp->fullCData(oldp+311,(6U),3);
}

VL_ATTR_COLD void Vtv80s___024root__trace_full_0_sub_0(Vtv80s___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtv80s___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_full_0\n"); );
    // Init
    Vtv80s___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtv80s___024root*>(voidSelf);
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtv80s___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtv80s___024root__trace_full_0_sub_0(Vtv80s___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtv80s__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtv80s___024root__trace_full_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.reset_n));
    bufp->fullBit(oldp+2,(vlSelfRef.clk));
    bufp->fullBit(oldp+3,(vlSelfRef.wait_n));
    bufp->fullBit(oldp+4,(vlSelfRef.int_n));
    bufp->fullBit(oldp+5,(vlSelfRef.nmi_n));
    bufp->fullBit(oldp+6,(vlSelfRef.busrq_n));
    bufp->fullBit(oldp+7,(vlSelfRef.m1_n));
    bufp->fullBit(oldp+8,(vlSelfRef.mreq_n));
    bufp->fullBit(oldp+9,(vlSelfRef.iorq_n));
    bufp->fullBit(oldp+10,(vlSelfRef.rd_n));
    bufp->fullBit(oldp+11,(vlSelfRef.wr_n));
    bufp->fullBit(oldp+12,(vlSelfRef.rfsh_n));
    bufp->fullBit(oldp+13,(vlSelfRef.halt_n));
    bufp->fullBit(oldp+14,(vlSelfRef.busak_n));
    bufp->fullSData(oldp+15,(vlSelfRef.A),16);
    bufp->fullCData(oldp+16,(vlSelfRef.di),8);
    bufp->fullCData(oldp+17,(vlSelfRef.dout),8);
    bufp->fullBit(oldp+18,(vlSelfRef.tv80s__DOT__reset_n));
    bufp->fullBit(oldp+19,(vlSelfRef.tv80s__DOT__clk));
    bufp->fullBit(oldp+20,(vlSelfRef.tv80s__DOT__wait_n));
    bufp->fullBit(oldp+21,(vlSelfRef.tv80s__DOT__int_n));
    bufp->fullBit(oldp+22,(vlSelfRef.tv80s__DOT__nmi_n));
    bufp->fullBit(oldp+23,(vlSelfRef.tv80s__DOT__busrq_n));
    bufp->fullBit(oldp+24,(vlSelfRef.tv80s__DOT__m1_n));
    bufp->fullBit(oldp+25,(vlSelfRef.tv80s__DOT__mreq_n));
    bufp->fullBit(oldp+26,(vlSelfRef.tv80s__DOT__iorq_n));
    bufp->fullBit(oldp+27,(vlSelfRef.tv80s__DOT__rd_n));
    bufp->fullBit(oldp+28,(vlSelfRef.tv80s__DOT__wr_n));
    bufp->fullBit(oldp+29,(vlSelfRef.tv80s__DOT__rfsh_n));
    bufp->fullBit(oldp+30,(vlSelfRef.tv80s__DOT__halt_n));
    bufp->fullBit(oldp+31,(vlSelfRef.tv80s__DOT__busak_n));
    bufp->fullSData(oldp+32,(vlSelfRef.tv80s__DOT__A),16);
    bufp->fullCData(oldp+33,(vlSelfRef.tv80s__DOT__di),8);
    bufp->fullCData(oldp+34,(vlSelfRef.tv80s__DOT__dout),8);
    bufp->fullBit(oldp+35,(vlSelfRef.tv80s__DOT__cen));
    bufp->fullBit(oldp+36,(vlSelfRef.tv80s__DOT__intcycle_n));
    bufp->fullBit(oldp+37,(vlSelfRef.tv80s__DOT__no_read));
    bufp->fullBit(oldp+38,(vlSelfRef.tv80s__DOT__write));
    bufp->fullBit(oldp+39,(vlSelfRef.tv80s__DOT__iorq));
    bufp->fullCData(oldp+40,(vlSelfRef.tv80s__DOT__di_reg),8);
    bufp->fullCData(oldp+41,(vlSelfRef.tv80s__DOT__mcycle),7);
    bufp->fullCData(oldp+42,(vlSelfRef.tv80s__DOT__tstate),7);
    bufp->fullBit(oldp+43,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__reset_n));
    bufp->fullBit(oldp+44,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__clk));
    bufp->fullBit(oldp+45,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__cen));
    bufp->fullBit(oldp+46,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__wait_n));
    bufp->fullBit(oldp+47,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__int_n));
    bufp->fullBit(oldp+48,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__nmi_n));
    bufp->fullBit(oldp+49,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__busrq_n));
    bufp->fullBit(oldp+50,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__m1_n));
    bufp->fullBit(oldp+51,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__iorq));
    bufp->fullBit(oldp+52,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__no_read));
    bufp->fullBit(oldp+53,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__write));
    bufp->fullBit(oldp+54,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__rfsh_n));
    bufp->fullBit(oldp+55,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__halt_n));
    bufp->fullBit(oldp+56,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__busak_n));
    bufp->fullSData(oldp+57,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__A),16);
    bufp->fullCData(oldp+58,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__dinst),8);
    bufp->fullCData(oldp+59,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__di),8);
    bufp->fullCData(oldp+60,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__dout),8);
    bufp->fullCData(oldp+61,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mc),7);
    bufp->fullCData(oldp+62,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ts),7);
    bufp->fullBit(oldp+63,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__intcycle_n));
    bufp->fullBit(oldp+64,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntE));
    bufp->fullBit(oldp+65,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__stop));
    bufp->fullCData(oldp+66,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ACC),8);
    bufp->fullCData(oldp+67,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__F),8);
    bufp->fullCData(oldp+68,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Ap),8);
    bufp->fullCData(oldp+69,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Fp),8);
    bufp->fullCData(oldp+70,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I),8);
    bufp->fullSData(oldp+71,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP),16);
    bufp->fullSData(oldp+72,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PC),16);
    bufp->fullCData(oldp+73,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegDIH),8);
    bufp->fullCData(oldp+74,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegDIL),8);
    bufp->fullSData(oldp+75,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusA),16);
    bufp->fullSData(oldp+76,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusB),16);
    bufp->fullSData(oldp+77,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusC),16);
    bufp->fullCData(oldp+78,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrA_r),3);
    bufp->fullCData(oldp+79,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrA),3);
    bufp->fullCData(oldp+80,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrB_r),3);
    bufp->fullCData(oldp+81,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrB),3);
    bufp->fullCData(oldp+82,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegAddrC),3);
    bufp->fullBit(oldp+83,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegWEH));
    bufp->fullBit(oldp+84,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegWEL));
    bufp->fullBit(oldp+85,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Alternate));
    bufp->fullSData(oldp+86,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__TmpAddr),16);
    bufp->fullCData(oldp+87,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IR),8);
    bufp->fullCData(oldp+88,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ISet),2);
    bufp->fullSData(oldp+89,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RegBusA_r),16);
    bufp->fullBit(oldp+90,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__reset_4x));
    bufp->fullSData(oldp+91,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ID16),16);
    bufp->fullCData(oldp+92,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Save_Mux),8);
    bufp->fullCData(oldp+93,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__tstate),7);
    bufp->fullCData(oldp+94,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mcycle),7);
    bufp->fullBit(oldp+95,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__last_mcycle));
    bufp->fullBit(oldp+96,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__last_tstate));
    bufp->fullBit(oldp+97,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntE_FF1));
    bufp->fullBit(oldp+98,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntE_FF2));
    bufp->fullBit(oldp+99,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Halt_FF));
    bufp->fullBit(oldp+100,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusReq_s));
    bufp->fullBit(oldp+101,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusAck));
    bufp->fullBit(oldp+102,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ClkEn));
    bufp->fullBit(oldp+103,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__NMI_s));
    bufp->fullBit(oldp+104,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__INT_s));
    bufp->fullCData(oldp+105,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IStatus),2);
    bufp->fullCData(oldp+106,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__DI_Reg),8);
    bufp->fullBit(oldp+107,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__T_Res));
    bufp->fullCData(oldp+108,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__XY_State),2);
    bufp->fullCData(oldp+109,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Pre_XY_F_M),3);
    bufp->fullBit(oldp+110,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__NextIs_XY_Fetch));
    bufp->fullBit(oldp+111,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__XY_Ind));
    bufp->fullBit(oldp+112,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__No_BTR));
    bufp->fullBit(oldp+113,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BTR_r));
    bufp->fullBit(oldp+114,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Auto_Wait));
    bufp->fullBit(oldp+115,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Auto_Wait_t1));
    bufp->fullBit(oldp+116,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Auto_Wait_t2));
    bufp->fullBit(oldp+117,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IncDecZ));
    bufp->fullCData(oldp+118,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusB),8);
    bufp->fullCData(oldp+119,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__BusA),8);
    bufp->fullCData(oldp+120,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ALU_Q),8);
    bufp->fullCData(oldp+121,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__F_Out),8);
    bufp->fullCData(oldp+122,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Read_To_Reg_r),5);
    bufp->fullBit(oldp+123,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Arith16_r));
    bufp->fullBit(oldp+124,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Z16_r));
    bufp->fullCData(oldp+125,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ALU_Op_r),4);
    bufp->fullBit(oldp+126,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Save_ALU_r));
    bufp->fullBit(oldp+127,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PreserveC_r));
    bufp->fullCData(oldp+128,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mcycles),3);
    bufp->fullCData(oldp+129,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__mcycles_d),3);
    bufp->fullCData(oldp+130,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__tstates),3);
    bufp->fullBit(oldp+131,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IntCycle));
    bufp->fullBit(oldp+132,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__NMICycle));
    bufp->fullBit(oldp+133,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Inc_PC));
    bufp->fullBit(oldp+134,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Inc_WZ));
    bufp->fullCData(oldp+135,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IncDec_16),4);
    bufp->fullCData(oldp+136,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Prefix),2);
    bufp->fullBit(oldp+137,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Read_To_Acc));
    bufp->fullBit(oldp+138,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Read_To_Reg));
    bufp->fullCData(oldp+139,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Set_BusB_To),4);
    bufp->fullCData(oldp+140,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Set_BusA_To),4);
    bufp->fullCData(oldp+141,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ALU_Op),4);
    bufp->fullBit(oldp+142,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Save_ALU));
    bufp->fullBit(oldp+143,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PreserveC));
    bufp->fullBit(oldp+144,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Arith16));
    bufp->fullCData(oldp+145,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Set_Addr_To),3);
    bufp->fullBit(oldp+146,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Jump));
    bufp->fullBit(oldp+147,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__JumpE));
    bufp->fullBit(oldp+148,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__JumpXY));
    bufp->fullBit(oldp+149,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Call));
    bufp->fullBit(oldp+150,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__RstP));
    bufp->fullBit(oldp+151,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__LDZ));
    bufp->fullBit(oldp+152,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__LDW));
    bufp->fullBit(oldp+153,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__LDSPHL));
    bufp->fullBit(oldp+154,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__iorq_i));
    bufp->fullBit(oldp+155,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__will_iorq));
    bufp->fullCData(oldp+156,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Special_LD),3);
    bufp->fullBit(oldp+157,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeDH));
    bufp->fullBit(oldp+158,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeRp));
    bufp->fullBit(oldp+159,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeAF));
    bufp->fullBit(oldp+160,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ExchangeRS));
    bufp->fullBit(oldp+161,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_DJNZ));
    bufp->fullBit(oldp+162,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_CPL));
    bufp->fullBit(oldp+163,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_CCF));
    bufp->fullBit(oldp+164,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_SCF));
    bufp->fullBit(oldp+165,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_RETN));
    bufp->fullBit(oldp+166,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_BT));
    bufp->fullBit(oldp+167,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_BC));
    bufp->fullBit(oldp+168,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_BTR));
    bufp->fullBit(oldp+169,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_RLD));
    bufp->fullBit(oldp+170,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_RRD));
    bufp->fullBit(oldp+171,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__I_INRC));
    bufp->fullBit(oldp+172,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SetDI));
    bufp->fullBit(oldp+173,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SetEI));
    bufp->fullCData(oldp+174,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__IMode),2);
    bufp->fullBit(oldp+175,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Halt));
    bufp->fullSData(oldp+176,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PC16),16);
    bufp->fullSData(oldp+177,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__PC16_B),16);
    bufp->fullSData(oldp+178,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP16),16);
    bufp->fullSData(oldp+179,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP16_A),16);
    bufp->fullSData(oldp+180,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__SP16_B),16);
    bufp->fullSData(oldp+181,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__ID16_B),16);
    bufp->fullBit(oldp+182,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__Oldnmi_n));
    bufp->fullBit(oldp+183,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Arith16));
    bufp->fullBit(oldp+184,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Z16));
    bufp->fullCData(oldp+185,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__ALU_Op),4);
    bufp->fullCData(oldp+186,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__IR),6);
    bufp->fullCData(oldp+187,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__ISet),2);
    bufp->fullCData(oldp+188,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BusA),8);
    bufp->fullCData(oldp+189,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BusB),8);
    bufp->fullCData(oldp+190,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__F_In),8);
    bufp->fullCData(oldp+191,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q),8);
    bufp->fullCData(oldp+192,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__F_Out),8);
    bufp->fullBit(oldp+193,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__UseCarry));
    bufp->fullBit(oldp+194,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Carry7_v));
    bufp->fullBit(oldp+195,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__OverFlow_v));
    bufp->fullBit(oldp+196,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__HalfCarry_v));
    bufp->fullBit(oldp+197,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Carry_v));
    bufp->fullCData(oldp+198,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q_v),8);
    bufp->fullCData(oldp+199,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__BitMask),8);
    bufp->fullCData(oldp+200,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__Q_t),8);
    bufp->fullSData(oldp+201,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_alu__DOT__DAA_Q),9);
    bufp->fullCData(oldp+202,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IR),8);
    bufp->fullCData(oldp+203,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ISet),2);
    bufp->fullCData(oldp+204,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycle),7);
    bufp->fullCData(oldp+205,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__F),8);
    bufp->fullBit(oldp+206,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__NMICycle));
    bufp->fullBit(oldp+207,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IntCycle));
    bufp->fullCData(oldp+208,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycles),3);
    bufp->fullCData(oldp+209,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__TStates),3);
    bufp->fullCData(oldp+210,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Prefix),2);
    bufp->fullBit(oldp+211,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_PC));
    bufp->fullBit(oldp+212,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_WZ));
    bufp->fullCData(oldp+213,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IncDec_16),4);
    bufp->fullBit(oldp+214,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Reg));
    bufp->fullBit(oldp+215,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Acc));
    bufp->fullCData(oldp+216,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusA_To),4);
    bufp->fullCData(oldp+217,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusB_To),4);
    bufp->fullCData(oldp+218,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ALU_Op),4);
    bufp->fullBit(oldp+219,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Save_ALU));
    bufp->fullBit(oldp+220,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__PreserveC));
    bufp->fullBit(oldp+221,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Arith16));
    bufp->fullCData(oldp+222,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_Addr_To),3);
    bufp->fullBit(oldp+223,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IORQ));
    bufp->fullBit(oldp+224,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__WILL_IORQ));
    bufp->fullBit(oldp+225,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Jump));
    bufp->fullBit(oldp+226,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpE));
    bufp->fullBit(oldp+227,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpXY));
    bufp->fullBit(oldp+228,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Call));
    bufp->fullBit(oldp+229,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__RstP));
    bufp->fullBit(oldp+230,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDZ));
    bufp->fullBit(oldp+231,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDW));
    bufp->fullBit(oldp+232,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__LDSPHL));
    bufp->fullCData(oldp+233,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Special_LD),3);
    bufp->fullBit(oldp+234,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeDH));
    bufp->fullBit(oldp+235,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRp));
    bufp->fullBit(oldp+236,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeAF));
    bufp->fullBit(oldp+237,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRS));
    bufp->fullBit(oldp+238,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_DJNZ));
    bufp->fullBit(oldp+239,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CPL));
    bufp->fullBit(oldp+240,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CCF));
    bufp->fullBit(oldp+241,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_SCF));
    bufp->fullBit(oldp+242,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RETN));
    bufp->fullBit(oldp+243,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BT));
    bufp->fullBit(oldp+244,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BC));
    bufp->fullBit(oldp+245,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BTR));
    bufp->fullBit(oldp+246,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RLD));
    bufp->fullBit(oldp+247,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RRD));
    bufp->fullBit(oldp+248,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__I_INRC));
    bufp->fullBit(oldp+249,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SetDI));
    bufp->fullBit(oldp+250,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SetEI));
    bufp->fullCData(oldp+251,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__IMode),2);
    bufp->fullBit(oldp+252,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Halt));
    bufp->fullBit(oldp+253,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__NoRead));
    bufp->fullBit(oldp+254,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__Write));
    bufp->fullCData(oldp+255,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__DDD),3);
    bufp->fullCData(oldp+256,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__SSS),3);
    bufp->fullCData(oldp+257,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_mcode__DOT__DPAIR),2);
    bufp->fullCData(oldp+258,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrC),3);
    bufp->fullCData(oldp+259,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOBH),8);
    bufp->fullCData(oldp+260,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrA),3);
    bufp->fullCData(oldp+261,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__AddrB),3);
    bufp->fullCData(oldp+262,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DIH),8);
    bufp->fullCData(oldp+263,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOAL),8);
    bufp->fullCData(oldp+264,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOCL),8);
    bufp->fullCData(oldp+265,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DIL),8);
    bufp->fullCData(oldp+266,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOBL),8);
    bufp->fullCData(oldp+267,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOCH),8);
    bufp->fullCData(oldp+268,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__DOAH),8);
    bufp->fullBit(oldp+269,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__clk));
    bufp->fullBit(oldp+270,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__CEN));
    bufp->fullBit(oldp+271,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__WEH));
    bufp->fullBit(oldp+272,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__WEL));
    bufp->fullCData(oldp+273,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[0]),8);
    bufp->fullCData(oldp+274,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[1]),8);
    bufp->fullCData(oldp+275,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[2]),8);
    bufp->fullCData(oldp+276,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[3]),8);
    bufp->fullCData(oldp+277,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[4]),8);
    bufp->fullCData(oldp+278,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[5]),8);
    bufp->fullCData(oldp+279,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[6]),8);
    bufp->fullCData(oldp+280,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[7]),8);
    bufp->fullCData(oldp+281,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[0]),8);
    bufp->fullCData(oldp+282,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[1]),8);
    bufp->fullCData(oldp+283,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[2]),8);
    bufp->fullCData(oldp+284,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[3]),8);
    bufp->fullCData(oldp+285,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[4]),8);
    bufp->fullCData(oldp+286,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[5]),8);
    bufp->fullCData(oldp+287,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[6]),8);
    bufp->fullCData(oldp+288,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[7]),8);
    bufp->fullCData(oldp+289,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__B),8);
    bufp->fullCData(oldp+290,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__C),8);
    bufp->fullCData(oldp+291,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__D),8);
    bufp->fullCData(oldp+292,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__E),8);
    bufp->fullCData(oldp+293,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__H),8);
    bufp->fullCData(oldp+294,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__L),8);
    bufp->fullSData(oldp+295,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__IX),16);
    bufp->fullSData(oldp+296,(vlSelfRef.tv80s__DOT__i_tv80_core__DOT__i_reg__DOT__IY),16);
}
