// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    VL_IN8(clk_sys,0,0);
    CData/*0:0*/ top__DOT__soc__DOT__fb_clk;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__ppu__lcd_ppu_en;
    CData/*0:0*/ top__DOT__soc__DOT__cpu_clock;
    CData/*0:0*/ top__DOT__soc__DOT__cpu_mreq_n;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__T80x__reset_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__cen;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Alternate;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__last_tstate;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IntE_FF1;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Halt_FF;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__BusAck;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__XY_Ind;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__BTR_r;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Auto_Wait_t1;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Arith16_r;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Z16_r;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Save_ALU_r;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IntCycle;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__NMICycle;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__JumpE;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__iorq_i;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ExchangeDH;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ExchangeRp;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_DJNZ;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__OverFlow_v;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__HalfCarry_v;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Carry_v;
    CData/*0:0*/ top__DOT__soc__DOT__wram_0__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__hram__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__clock_b;
    VL_OUT8(VGA_R,7,0);
    VL_OUT8(VGA_B,7,0);
    VL_OUT8(VGA_G,7,0);
    VL_OUT8(VGA_HS,0,0);
    VL_OUT8(VGA_VS,0,0);
    VL_OUT8(VGA_HB,0,0);
    VL_OUT8(VGA_VB,0,0);
    VL_IN8(reset,0,0);
    VL_IN8(clk_vid,0,0);
    VL_IN8(ioctl_download,0,0);
    VL_IN8(ioctl_dout,7,0);
    VL_IN8(ioctl_index,7,0);
    VL_OUT8(ioctl_wait,0,0);
    VL_IN8(ioctl_wr,0,0);
    CData/*7:0*/ top__DOT__VGA_R;
    CData/*7:0*/ top__DOT__VGA_B;
    CData/*7:0*/ top__DOT__VGA_G;
    CData/*0:0*/ top__DOT__VGA_HS;
    CData/*0:0*/ top__DOT__VGA_VS;
    CData/*0:0*/ top__DOT__VGA_HB;
    CData/*0:0*/ top__DOT__VGA_VB;
    CData/*0:0*/ top__DOT__reset;
    CData/*0:0*/ top__DOT__clk_sys;
    CData/*0:0*/ top__DOT__clk_vid;
    CData/*0:0*/ top__DOT__ioctl_download;
    CData/*7:0*/ top__DOT__ioctl_dout;
    CData/*7:0*/ top__DOT__ioctl_index;
    CData/*0:0*/ top__DOT__ioctl_wait;
    CData/*0:0*/ top__DOT__ioctl_wr;
    CData/*0:0*/ top__DOT__VGA_DE;
    CData/*0:0*/ top__DOT__soc__DOT__clk_sys;
    CData/*0:0*/ top__DOT__soc__DOT__pixel_clock;
    CData/*0:0*/ top__DOT__soc__DOT__VGA_HS;
    CData/*0:0*/ top__DOT__soc__DOT__VGA_VS;
    CData/*7:0*/ top__DOT__soc__DOT__VGA_R;
    CData/*7:0*/ top__DOT__soc__DOT__VGA_G;
    CData/*7:0*/ top__DOT__soc__DOT__VGA_B;
    CData/*0:0*/ top__DOT__soc__DOT__VGA_HB;
    CData/*0:0*/ top__DOT__soc__DOT__VGA_VB;
    CData/*0:0*/ top__DOT__soc__DOT__VGA_DE;
    CData/*3:0*/ top__DOT__soc__DOT__r;
    CData/*3:0*/ top__DOT__soc__DOT__g;
    CData/*3:0*/ top__DOT__soc__DOT__b;
    CData/*0:0*/ top__DOT__soc__DOT__vs;
    CData/*0:0*/ top__DOT__soc__DOT__hs;
    CData/*0:0*/ top__DOT__soc__DOT__ce_pix;
    CData/*0:0*/ top__DOT__soc__DOT__hblank;
    CData/*0:0*/ top__DOT__soc__DOT__vblank;
    CData/*0:0*/ top__DOT__soc__DOT__interlace;
    CData/*7:0*/ top__DOT__soc__DOT__ppu_LY;
    CData/*0:0*/ top__DOT__soc__DOT__fb_wr;
    CData/*7:0*/ top__DOT__soc__DOT__fb_data;
    CData/*7:0*/ top__DOT__soc__DOT__ppu_vram0_data;
    CData/*7:0*/ top__DOT__soc__DOT__ppu_vram1_data;
    CData/*7:0*/ top__DOT__soc__DOT__cpu_reset_cnt;
    CData/*0:0*/ top__DOT__soc__DOT__cpu_reset;
    CData/*7:0*/ top__DOT__soc__DOT__cpu_din;
    CData/*7:0*/ top__DOT__soc__DOT__cpu_dout;
    CData/*0:0*/ top__DOT__soc__DOT__cpu_rd_n;
    CData/*0:0*/ top__DOT__soc__DOT__cpu_wr_n;
    CData/*7:0*/ top__DOT__soc__DOT__rom_data_out;
    CData/*7:0*/ top__DOT__soc__DOT__vram_data_out;
    CData/*7:0*/ top__DOT__soc__DOT__vram0_data_out;
    CData/*7:0*/ top__DOT__soc__DOT__vram1_data_out;
    CData/*0:0*/ top__DOT__soc__DOT__vram0_sel;
    CData/*7:0*/ top__DOT__soc__DOT__wram0_data_out;
    CData/*7:0*/ top__DOT__soc__DOT__wramN_data_out;
    CData/*7:0*/ top__DOT__soc__DOT__hram_data_out;
    CData/*7:0*/ top__DOT__soc__DOT__io_vbk;
    CData/*7:0*/ top__DOT__soc__DOT__io_lcdc;
    CData/*7:0*/ top__DOT__soc__DOT__io_svbk;
    CData/*2:0*/ top__DOT__soc__DOT__wram_sel;
    CData/*7:0*/ top__DOT__soc__DOT__io_bgp;
    CData/*1:0*/ top__DOT__soc__DOT__bgp_id3;
    CData/*1:0*/ top__DOT__soc__DOT__bgp_id2;
    CData/*1:0*/ top__DOT__soc__DOT__bgp_id1;
    CData/*1:0*/ top__DOT__soc__DOT__bgp_id0;
    CData/*0:0*/ top__DOT__soc__DOT__hram_sel;
    CData/*0:0*/ top__DOT__soc__DOT__vram_sel;
    CData/*0:0*/ top__DOT__soc__DOT__io_sel;
    CData/*0:0*/ top__DOT__soc__DOT__wram_0_sel;
    CData/*0:0*/ top__DOT__soc__DOT__wram_n_group_sel;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram_0__wren_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__vram_0__wren_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__vram_1__wren_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__hram__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT____Vcellout__wram___BRA__1__KET____DOT__wram_N__q_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram___BRA__1__KET____DOT__wram_N__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT____Vcellout__wram___BRA__2__KET____DOT__wram_N__q_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram___BRA__2__KET____DOT__wram_N__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT____Vcellout__wram___BRA__3__KET____DOT__wram_N__q_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram___BRA__3__KET____DOT__wram_N__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT____Vcellout__wram___BRA__4__KET____DOT__wram_N__q_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram___BRA__4__KET____DOT__wram_N__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT____Vcellout__wram___BRA__5__KET____DOT__wram_N__q_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram___BRA__5__KET____DOT__wram_N__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT____Vcellout__wram___BRA__6__KET____DOT__wram_N__q_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram___BRA__6__KET____DOT__wram_N__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT____Vcellout__wram___BRA__7__KET____DOT__wram_N__q_a;
    CData/*0:0*/ top__DOT__soc__DOT____Vcellinp__wram___BRA__7__KET____DOT__wram_N__wren_a;
    CData/*0:0*/ top__DOT__soc__DOT____VdfgRegularize_hc3a4b302_4_3;
    CData/*0:0*/ top__DOT__soc__DOT____VdfgRegularize_hc3a4b302_4_4;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__clk;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__lcd_ppu_en;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__window_tile_map;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__window_en;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__bg_window_tile;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__bg_tile_map;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__obj_size;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__obj_en;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__bg_win_prio;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__fb_clk;
    CData/*0:0*/ top__DOT__soc__DOT__ppu__DOT__fb_wr;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__fb_data;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__vram0_data;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__vram1_data;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__LY;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__LX;
    CData/*2:0*/ top__DOT__soc__DOT__ppu__DOT__mode;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__step;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__pixel_buf;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__tile_id;
    CData/*1:0*/ top__DOT__soc__DOT__ppu__DOT__tick;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__tileX;
    CData/*7:0*/ top__DOT__soc__DOT__ppu__DOT__tileY;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__pclk;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb_clk;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb_wr;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__fb_data;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__hs;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__vs;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__r;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__g;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__b;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__VGA_HB;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__VGA_VB;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__VGA_DE;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__hblank;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__vblank;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__pixel;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__de;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__show_black;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__m1_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__mreq_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__iorq_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__rd_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__wr_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__rfsh_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__halt_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__busak_n;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__dout;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__reset_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__clk;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__wait_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__int_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__nmi_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__busrq_n;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__di;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__intcycle_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__no_read;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__write;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__iorq;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__di_reg;
    CData/*6:0*/ top__DOT__soc__DOT__T80x__DOT__mcycle;
    CData/*6:0*/ top__DOT__soc__DOT__T80x__DOT__tstate;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__m1_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__iorq;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__no_read;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__write;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__rfsh_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__halt_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__busak_n;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__dout;
    CData/*6:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__mc;
    CData/*6:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ts;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__intcycle_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IntE;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__stop;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__reset_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__clk;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__cen;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__wait_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__int_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__nmi_n;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__busrq_n;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__dinst;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__di;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ACC;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__F;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Ap;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Fp;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegDIH;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegDIL;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegAddrA_r;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegAddrA;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegAddrB_r;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegAddrB;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegAddrC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegWEH;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegWEL;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IR;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ISet;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Save_Mux;
    CData/*6:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__tstate;
    CData/*6:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__mcycle;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__last_mcycle;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IntE_FF2;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__BusReq_s;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ClkEn;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__NMI_s;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__INT_s;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IStatus;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__DI_Reg;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__T_Res;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__XY_State;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Pre_XY_F_M;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__NextIs_XY_Fetch;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__No_BTR;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Auto_Wait;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Auto_Wait_t2;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IncDecZ;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__BusB;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__BusA;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ALU_Q;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__F_Out;
    CData/*4:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Read_To_Reg_r;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ALU_Op_r;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__PreserveC_r;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__mcycles;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__mcycles_d;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__tstates;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Inc_PC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Inc_WZ;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IncDec_16;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Prefix;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Read_To_Acc;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Read_To_Reg;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Set_BusB_To;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Set_BusA_To;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ALU_Op;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Save_ALU;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__PreserveC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Arith16;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Set_Addr_To;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Jump;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__JumpXY;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Call;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RstP;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__LDZ;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__LDW;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__LDSPHL;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Special_LD;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ExchangeAF;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ExchangeRS;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_CPL;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_CCF;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_SCF;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_RETN;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_BT;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_BC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_BTR;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_RLD;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_RRD;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__I_INRC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__SetDI;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__SetEI;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IMode;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Halt;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Oldnmi_n;
    CData/*5:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT____Vcellinp__i_alu__IR;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycles;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__TStates;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Prefix;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_PC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_WZ;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__IncDec_16;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Reg;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Acc;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusA_To;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusB_To;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__ALU_Op;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Save_ALU;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__PreserveC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Arith16;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_Addr_To;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__IORQ;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Jump;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpE;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpXY;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Call;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__RstP;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__LDZ;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__LDW;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__LDSPHL;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Special_LD;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeDH;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRp;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeAF;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRS;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_DJNZ;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CPL;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CCF;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_SCF;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RETN;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BT;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BTR;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RLD;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RRD;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__I_INRC;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__SetDI;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__SetEI;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__IMode;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Halt;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__NoRead;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Write;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__IR;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__ISet;
    CData/*6:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycle;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__F;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__NMICycle;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__IntCycle;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__DDD;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__SSS;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__DPAIR;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Q;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__F_Out;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Arith16;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Z16;
    CData/*3:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__ALU_Op;
    CData/*5:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__IR;
    CData/*1:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__ISet;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__BusA;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__BusB;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__F_In;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__UseCarry;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Carry7_v;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Q_v;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__BitMask;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Q_t;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DOBH;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DOAL;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DOCL;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DOBL;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DOCH;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DOAH;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__AddrC;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__AddrA;
    CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__AddrB;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DIH;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__DIL;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__clk;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__CEN;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__WEH;
    CData/*0:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__WEL;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__B;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__C;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__D;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__E;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__H;
    CData/*7:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__L;
    CData/*0:0*/ top__DOT__soc__DOT__rom__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__rom__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__rom__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__rom__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__rom__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__rom__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__rom__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__rom__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__rom__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__rom__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram_0__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram_0__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram_0__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram_0__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram_0__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram_0__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram_0__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram_0__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram_0__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__vram_0__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__vram_0__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__vram_0__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__vram_0__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__vram_0__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__vram_0__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__vram_0__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__vram_0__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__vram_0__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__vram_0__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__vram_1__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__vram_1__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__vram_1__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__vram_1__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__vram_1__DOT__clock_b;
    CData/*0:0*/ top__DOT__soc__DOT__vram_1__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__vram_1__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__vram_1__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__vram_1__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__vram_1__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__hram__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__hram__DOT__wren_a;
    CData/*6:0*/ top__DOT__soc__DOT__hram__DOT__address_a;
    CData/*7:0*/ top__DOT__soc__DOT__hram__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__hram__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__hram__DOT__wren_b;
    CData/*6:0*/ top__DOT__soc__DOT__hram__DOT__address_b;
    CData/*7:0*/ top__DOT__soc__DOT__hram__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__hram__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__hram__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__hram__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__byteena_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__clock_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__wren_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__data_a;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__q_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__wren_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__data_b;
    CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__q_b;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__byteena_a;
    CData/*0:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__byteena_b;
    CData/*7:0*/ __Vdly__top__DOT__soc__DOT__ppu__DOT__pixel_buf;
    CData/*2:0*/ __Vdly__top__DOT__soc__DOT__ppu__DOT__mode;
    CData/*7:0*/ __Vdly__top__DOT__soc__DOT__ppu__DOT__step;
    CData/*7:0*/ __Vdly__top__DOT__soc__DOT__ppu__DOT__LX;
    CData/*1:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__XY_State;
    CData/*7:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IR;
    CData/*7:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ACC;
    CData/*7:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__F;
    CData/*0:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Auto_Wait_t1;
    CData/*0:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Auto_Wait_t2;
    CData/*0:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IntE_FF1;
    CData/*0:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IntE_FF2;
    CData/*6:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__tstate;
    CData/*2:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Pre_XY_F_M;
    CData/*6:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__mcycle;
    CData/*0:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__NMICycle;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram_0__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram_0__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__vram_0__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__vram_0__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__vram_1__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__vram_1__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__hram__DOT__mem__v0;
    CData/*6:0*/ __VdlyDim0__top__DOT__soc__DOT__hram__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__hram__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__mem__v0;
    CData/*7:0*/ __VdlyVal__top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VdlySet__top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__mem__v0;
    CData/*0:0*/ __VstlFirstIteration;
    CData/*0:0*/ __VicoFirstIteration;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__cpu_clock__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__cpu_mreq_n__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT____Vcellinp__ppu__lcd_ppu_en__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__clk_sys__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__fb_clk__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT____Vcellinp__T80x__reset_n__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__F__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IR__0;
    CData/*1:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ISet__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IntCycle__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__NMICycle__0;
    CData/*6:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__mcycle__0;
    CData/*3:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ALU_Op_r__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__BusA__0;
    CData/*7:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__BusB__0;
    CData/*5:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT____Vcellinp__i_alu__IR__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram_0__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__hram__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__clock_b__0;
    CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__clock_b__0;
    CData/*0:0*/ __VactDidInit;
    CData/*0:0*/ __VactContinue;
    SData/*14:0*/ top__DOT__soc__DOT__fb_addr;
    SData/*13:0*/ top__DOT__soc__DOT__ppu_vram0_addr;
    SData/*13:0*/ top__DOT__soc__DOT__ppu_vram1_addr;
    SData/*15:0*/ top__DOT__soc__DOT__cpu_addr;
    SData/*14:0*/ top__DOT__soc__DOT__ppu__DOT__fb_addr;
    SData/*13:0*/ top__DOT__soc__DOT__ppu__DOT__vram0_addr;
    SData/*13:0*/ top__DOT__soc__DOT__ppu__DOT__vram1_addr;
    SData/*14:0*/ top__DOT__soc__DOT__vga__DOT__fb_addr;
    SData/*9:0*/ top__DOT__soc__DOT__vga__DOT__h_cnt;
    SData/*9:0*/ top__DOT__soc__DOT__vga__DOT__v_cnt;
    SData/*15:0*/ top__DOT__soc__DOT__vga__DOT__video_counter;
    SData/*15:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__address_a;
    SData/*15:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__address_b;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__A;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__A;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__SP;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__PC;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegBusA;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegBusB;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegBusC;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__TmpAddr;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__RegBusA_r;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ID16;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__PC16;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__PC16_B;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__SP16;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__SP16_A;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__SP16_B;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__ID16_B;
    SData/*8:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__DAA_Q;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__IX;
    SData/*15:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__IY;
    SData/*11:0*/ top__DOT__soc__DOT__rom__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__rom__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram_0__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram_0__DOT__address_b;
    SData/*12:0*/ top__DOT__soc__DOT__vram_0__DOT__address_a;
    SData/*12:0*/ top__DOT__soc__DOT__vram_0__DOT__address_b;
    SData/*12:0*/ top__DOT__soc__DOT__vram_1__DOT__address_a;
    SData/*12:0*/ top__DOT__soc__DOT__vram_1__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__address_b;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__address_a;
    SData/*11:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__address_b;
    SData/*13:0*/ __Vdly__top__DOT__soc__DOT__ppu_vram0_addr;
    SData/*13:0*/ __Vdly__top__DOT__soc__DOT__ppu_vram1_addr;
    SData/*15:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__PC;
    SData/*15:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__TmpAddr;
    SData/*15:0*/ __Vdly__top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__SP;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram_0__DOT__mem__v0;
    SData/*12:0*/ __VdlyDim0__top__DOT__soc__DOT__vram_0__DOT__mem__v0;
    SData/*12:0*/ __VdlyDim0__top__DOT__soc__DOT__vram_1__DOT__mem__v0;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__mem__v0;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__mem__v0;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__mem__v0;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__mem__v0;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__mem__v0;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__mem__v0;
    SData/*11:0*/ __VdlyDim0__top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__mem__v0;
    VL_IN(ioctl_addr,24,0);
    IData/*24:0*/ top__DOT__ioctl_addr;
    IData/*31:0*/ __VactIterCount;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<25> __VactTriggered;
    VlTriggerVec<25> __VnbaTriggered;
    VlUnpacked<CData/*7:0*/, 7> top__DOT__soc__DOT__wramN_q_a;
    VlUnpacked<CData/*7:0*/, 65536> top__DOT__soc__DOT__vga__DOT__fb__DOT__mem;
    VlUnpacked<CData/*7:0*/, 8> top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH;
    VlUnpacked<CData/*7:0*/, 8> top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__rom__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram_0__DOT__mem;
    VlUnpacked<CData/*7:0*/, 8192> top__DOT__soc__DOT__vram_0__DOT__mem;
    VlUnpacked<CData/*7:0*/, 8192> top__DOT__soc__DOT__vram_1__DOT__mem;
    VlUnpacked<CData/*7:0*/, 128> top__DOT__soc__DOT__hram__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__mem;
    VlUnpacked<CData/*7:0*/, 4096> top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__mem;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__init_file = 0U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__aNone = 7U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__aBC = 0U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__aDE = 1U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__aXY = 2U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__aIOA = 4U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__aSP = 5U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__aZI = 6U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__aNone = 7U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__aBC = 0U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__aDE = 1U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__aXY = 2U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__aIOA = 4U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__aSP = 5U;
    static constexpr CData/*2:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__aZI = 6U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram_0__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__vram_0__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__vram_1__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__hram__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__init_file = 0U;
    static constexpr CData/*7:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__init_file = 0U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__H = 0x00000300U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__HFP = 0x00000018U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__HS = 0x00000050U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__HBP = 0x00000068U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__V = 0x00000240U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__VFP = 1U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__VS = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__VBP = 0x00000011U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vga__DOT__fb__DOT__widthad_a = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__T2Write = 1U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__IOWait = 1U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__IOWait = 1U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_C = 0U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_N = 1U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_P = 2U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_X = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_H = 4U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_Y = 5U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_Z = 6U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__Flag_S = 7U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_C = 0U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_N = 1U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_P = 2U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_X = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_H = 4U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_Y = 5U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_Z = 6U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_mcode__DOT__Flag_S = 7U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Mode = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_C = 0U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_N = 1U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_P = 2U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_X = 3U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_H = 4U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_Y = 5U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_Z = 6U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__T80x__DOT__i_tv80_core__DOT__i_alu__DOT__Flag_S = 7U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__rom__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__rom__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram_0__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram_0__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vram_0__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vram_0__DOT__widthad_a = 0x0000000dU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vram_1__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__vram_1__DOT__widthad_a = 0x0000000dU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__hram__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__hram__DOT__widthad_a = 7U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__1__KET____DOT__wram_N__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__2__KET____DOT__wram_N__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__3__KET____DOT__wram_N__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__4__KET____DOT__wram_N__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__5__KET____DOT__wram_N__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__6__KET____DOT__wram_N__DOT__widthad_a = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__width_a = 8U;
    static constexpr IData/*31:0*/ top__DOT__soc__DOT__wram___BRA__7__KET____DOT__wram_N__DOT__widthad_a = 0x0000000cU;
    static constexpr QData/*55:0*/ top__DOT__soc__DOT__rom__DOT__init_file = 0x006762612e686578ULL;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
